# Generated by Django 6.1 on 2026-08-18 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_question_question_text_choice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="voted_users",
            field=models.ManyToManyField(
                blank=True, related_name="voted_questions", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
